name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build the package
        run: poetry build

      - name: Publish package to PyPI
        env:
          TWINE_API_KEY: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --username __token__ --password $TWINE_API_KEY
